name: Build & Push OCI Image to Registry

on:
  workflow_call:
    inputs:
      workdirs:
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        workdir: ${{ fromJSON(inputs.workdirs) }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up QEMU for Docker Buildx
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1

      - name: Set up Node.js for extracting recipe from Dockerfile
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 18
          check-latest: true

      - name: Install meow dependencies for extracting recipe from Dockerfile
        run: npm i --no-save meow@11.x

      - name: Extract recipe from Dockerfile
        id: recipe
        run: |
          TAGS=`node ${{ github.workspace }}/extractImage.mjs ${{ matrix.workdir }}/Dockerfile tags`
          PLATFORMS=`node ${{ github.workspace }}/extractImage.mjs ${{ matrix.workdir }}/Dockerfile platforms`
          VARIANT=`node ${{ github.workspace }}/extractImage.mjs ${{ matrix.workdir }}/Dockerfile variant`
          echo TAGS: $TAGS
          echo PLATFORMS: $PLATFORMS
          echo VARIANT: $VARIANT
          echo "::set-output name=tags::${TAGS//$', '/'%0A'}"
          echo "::set-output name=platforms::${PLATFORMS//$', '/'%0A'}"
          echo "::set-output name=variant::$VARIANT"

      - name: Generate Docker image metadata
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        id: meta
        with:
          images: |
            docker.io/fabio0107/node
            ghcr.io/fab1o0107/node
          tags: |
            ${{ steps.recipe.outputs.tags }}

      - name: Login to Docker Hub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: fabio0107
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image from the specified Dockerfile
        id: docker_build
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
        with:
          context: ${{ matrix.workdir }}
          platforms: |
            ${{ steps.recipe.outputs.platforms }}
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
