name: Build & Push Node.js 21 to OCI Image Registry

on:
  push:
    branches:
      - main
    paths:
      - "21/**/Dockerfile"
  pull_request:
    branches:
      - main
    paths:
      - "21/**/Dockerfile"

jobs:
  workdirs:
    uses: ./.github/workflows/specify-workdir.yml
    with:
      base-dir: 21

  image:
    uses: ./.github/workflows/build.yml
    needs: workdirs
    with:
      workdirs: ${{ needs.workdirs.outputs.workdirs-array }}
    secrets:
      docker-token: ${{ secrets.DOCKER_TOKEN }}
      github-username: ${{ github.repository_owner }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
