name: Build & Push Node.js 19 to OCI Image Registry

on:
  push:
    branches:
      - main
    paths:
      - "19/**/Dockerfile"
      - extractImage.mjs
  pull_request:
    branches:
      - main
    paths:
      - "19/**/Dockerfile"
      - extractImage.mjs

jobs:
  workdirs:
    uses: ./.github/workflows/specify-workdir.yml
    with:
      base-dir: 19

  image:
    uses: ./.github/workflows/build.yml
    needs: workdirs
    with:
      workdirs: ${{ needs.workdirs.outputs.workdirs-array }}
