name: Specify Dockerfile working directories

on:
  workflow_call:
    inputs:
      base-dir:
        required: true
        type: string
    outputs:
      workdirs:
        description: "List of working directories"
        value: ${{ jobs.specify-workdir.outputs.workdirs }}
      workdirs-array:
        description: "List of working directories in JSON Array"
        value: ${{ jobs.specify-workdir.outputs.workdirs-array }}

permissions:
  contents: read

jobs:
  specify-workdir:
    runs-on: ubuntu-latest

    outputs:
      workdirs: ${{ steps.workdirs.outputs.list }}
      workdirs-array: ${{ steps.array.outputs.result }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Node.js for generating JSON Array
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 18
          check-latest: true

      - name: Generate a list of changed Dockerfiles
        id: workdirs
        run: echo "list=$(git --no-pager diff --name-only HEAD^ ${{ inputs.base-dir }} | sed 's/\/Dockerfile//g' | sed ':a;N;$!ba;s/\n/ /g')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Generate a JSON array of list
        id: array
        run: echo "result=$(node -p 'JSON.stringify(process.argv.slice(1))' ${{ steps.workdirs.outputs.list }})" >> $GITHUB_OUTPUT
